version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: g3erVpeUgEUNh8Fj
    volumes:
      - ./create-table.sql:/docker-entrypoint-initdb.d/create-table.sql

  cats-api:
    build: ./cats-api
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080